#!/bin/bash

# Define the target output directory
OUT_DIR="./output"

# CLEAN UP PREPROCESSING AND SOLVER BUILDS
echo "Cleaning up compilation files..."

if [ -d "01_pre_processor" ]; then
    echo "Cleaning 01_pre_processor..."
    make -C 01_pre_processor clean
else
    echo "Warning: 01_pre_processor directory not found."
fi

if [ -d "02_solver" ]; then
    echo "Cleaning 02_solver..."
    make -C 02_solver clean
else
    echo "Warning: 02_solver directory not found."
fi

if [ -d "03_post_processor" ]; then
    echo "Cleaning 03_post_processor..."
    make -C 03_post_processor clean
    make -C 03_post_processor/inst clean
    make -C 03_post_processor/avg clean
else
    echo "Warning: 03_post_processor directory not found."
fi

# COMPLETE RESET: Check if the directory exists, and if so, wipe it.
if [ -d "$OUT_DIR" ]; then
    echo "Resetting: Removing existing '$OUT_DIR' directory and old data..."
    rm -rf "$OUT_DIR"
fi

echo "Initializing clean '$OUT_DIR' root directory..."

# INITIALIZATION: Create only the root output directory.
# Per-case subdirectories are created by the dimple generator pipeline.
mkdir -p "$OUT_DIR"

echo "Initialization complete. Only '$OUT_DIR' root was created; case subdirectories will be generated by the pipeline at runtime."